name: Github Actions 실행해보기

# Event : 실행되는 시점을 설정
# main이라는 브랜치에 push될 때 아래 WorkFlow를 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 job으로 구성됩니다.
# 여러 job은 기본적으로 병렬적으로 수행 된다.
jobs:
  # job을 식별하기 위한 id
  My-Deploy-Job:
    # ubuntu 환경 / 가장 최신 버전
    runs-on: ubuntu-latest

    # Step : 특정 작업을 수행하는 가장 작은 단위
    steps:
      - name: Hello World 찍기
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: | 
          echo "Good"
          echo "Morning"
                    

      - name : github Actions 자체에 저장되어 있는 변수 사용
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY